spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: ORDER_SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER_SERVICE
                fallbackuri: forward:/orderServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: Payment-Service
          uri: http://localhost:8081
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: Payment-Service
                fallbackuri: forward:/paymentServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: product-service
          uri: http://localhost:8080
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackuri: forward:/productServiceFallBack
            - name: RequestRateLimiter
              args:
                #one request allowed per second
                redis-rate-limiter.replenishRate: 1
                #how many requests in that one particular second
                redis-rate-limiter.burstCapacity: 1


server:
  port: 9090
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    reactor.netty: DEBUG

